### ISSUE TITLE
Need to add Acknowledgements

### ISSUE THREAD

**Issue by bnmnetp** [barbarer/ThinkCPP#6]
This book is licensed CC-BY-NC -- So we need to add an Acknowledgements section like we have in thinkcspy and make sure we are clearly acknowledging Allen Downey as the original author.

Also we should add the CC-BY-NC badge on the TOC page.

This should be done ASAP as it is on academy now.

**Comment by barbarer** [comment]
I will do it today.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
I have added an Acknowledgements section.  I had it in the repo's Readme as
well.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
We have added this.
